name: Sync2

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v5

      - name: Push to destination repository
        run: |
          git config --global user.email "your email"
          git config --global user.name "your user name"
          git clone https://x-access-token:${{ secrets.PAT_TEST }}@github.com/HajosB144/MockPrivate.git
          cd MockPrivate
          git remote add public https://github.com/HajosB144/MockPublic.git
          git remote update
          git merge public/main -X theirs -m "Sync from public repository"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TEST }}